services:
  db:
    image: postgres:16-alpine
    container_name: classroom-db
    environment:
      POSTGRES_DB: class
      POSTGRES_USER: guisandroni
      POSTGRES_PASSWORD: class
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guisandroni -d class"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./spring-api
    container_name: classroom-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/class
      SPRING_DATASOURCE_USERNAME: guisandroni
      SPRING_DATASOURCE_PASSWORD: class
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./front-end
    container_name: classroom-front
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
