services:
  db:
    image: 'postgres:latest'
    container_name: ClassrommDB
    environment:
        POSTGRES_DB: class
        POSTGRES_PASSWORD: class
        POSTGRES_USER: guisandroni
    ports:
      - '5432:5432'
    volumes:
        - 'postgres_data:/var/lib/postgresql/data'


volumes:
    postgres_data:
