spring:
  application:
    name: classroom-management

  profiles:
    active: prod

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvblRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZzIwMjQ=}
  expiration: 86400000
